# file: postgresql/tasks/extensions/contrib.yml

- name: Extensions | Make sure the postgres contrib extensions are installed via apt
  apt:
    name: "postgresql-contrib-{{postgresql_version}}"
    state: present
  when: ansible_pkg_mgr == "apt"
  notify:
    - restart postgresql

- name: Extensions | Make sure the postgres contrib extensions are installed via yum
  yum:
    name: "postgresql{{postgresql_version_major}}{{postgresql_version_minor}}-contrib"
    state: present
  when: ansible_pkg_mgr == "yum"
  notify:
    - restart postgresql
