# file: postgresql/tasks/main.yml

- include_tasks: install_debian.yml
  when: ansible_os_family == 'Debian'
  tags: [postgresql, postgresql-install]

- include_tasks: install_redhat.yml
  when: ansible_os_family == 'RedHat'
  tags: [postgresql, postgresql-install]

- import_tasks: extensions.yml
  tags: [postgresql, postgresql-extensions]

- import_tasks: configure.yml
  tags: [postgresql, postgresql-configure]

- import_tasks: databases.yml
  tags: [postgresql, postgresql-databases]

- import_tasks: users.yml
  tags: [postgresql, postgresql-users]

- include_tasks: monit.yml
  when: monit_protection is defined and monit_protection == true
  tags: [postgresql, postgresql-monit]
