# file: postgresql/tasks/main.yml

- include: install_debian.yml
  when: ansible_os_family == 'Debian'
- include: install_redhat.yml
  when: ansible_os_family == 'RedHat'
- include: extensions.yml
- include: configure.yml
- include: databases.yml
- include: users.yml
- include: monit.yml
  when: monit_protection is defined and monit_protection == true
