# file: postgresql/tasks/users.yml

- name: Users | Ensure PostgreSQL is running
  service:
    name: "{{ [ansible_os_family]|map('extract', {'Debian': 'postgresql', 'RedHat': ['postgresql', postgresql_version] | join('-')})|list|first }}"
    state: started

- name: Users | Make sure the PostgreSQL users are present
  postgresql_user:
    name: "{{item.name}}"
    password: "{{item.pass | default('pass')}}"
    state: present
    login_host: "{{item.host | default('localhost')}}"
  with_items: "{{ postgresql_users }}"
  when: postgresql_users|length > 0
  no_log: true

- name: Users | Update the user privileges
  postgresql_user:
    name: "{{item.name}}"
    db: "{{item.db}}"
    priv: "{{item.priv | default('ALL')}}"
    state: present
    login_host: "{{item.host | default('localhost')}}"
  with_items: "{{ postgresql_user_privileges }}"
  when: postgresql_users|length > 0
